services:
  web:
    build: ./web
    ports:
      - 8080:80
    depends_on:
      - words
    volumes:
      - ./web/static:/app/static

  words:
    build: ./words
    depends_on:
      - db

  db:
    build: ./db
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
